### ISSUE TITLE
Error writing model to file in Android

### ISSUE THREAD

**Issue by mouri11** [AlexTitovWork/NLPclassifier#3]
I am trying to [write out the trained model to file](https://github.com/AlexTitovWork/NLPclassifier/blob/master/src/main/java/NLPClassifier.java#L122). 

I am able to read the .bin and .dat files, but not able to write it out. I keep getting the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.alertme, PID: 12628
    java.lang.NullPointerException: Attempt to get length of null array
        at java.io.FilterOutputStream.write(FilterOutputStream.java:103)
        at opennlp.tools.util.model.ByteArraySerializer.serialize(ByteArraySerializer.java:31)
        at opennlp.tools.util.model.ByteArraySerializer.serialize(ByteArraySerializer.java:24)
        at opennlp.tools.util.model.BaseModel.serialize(BaseModel.java:597)
        at com.example.alertme.NLPClassifier.makeDataTrainingModel(NLPClassifier.java:168)
```
This is what I have tried so far:
```
new BufferedOutputStream(new FileOutputStream(currentDir + "example-bad-model.dat"));
new File(getFilesDir(), "example-bad-model.dat");
new FileOutputStream(getFilesDir().toString() + "/example-bad-model.dat");
openFileOutput("example-bad-model.dat", Context.MODE_PRIVATE);
```

None of the above worked. I keep getting the same exception. Any suggestions or pointers would be appreciated. Thanks.

**Comment by AlexTitovWork** [comment]
Hello @mouri11 , i'll check this.

**Comment by AlexTitovWork** [comment]
I used  under Ubuntu IntelliJ IDEA, all stable worked.
Lets try to generate and test base model in main file "NlpProductClassifier.java"
If all  ok,  try to use pats of code separately.
Try to use double slash or directly specify path, may be IDE interpretation path \\, // problem.
```
OutputStream modelOut = null;
        try {
            String currentDir = new File("").getAbsolutePath();
            modelOut = new BufferedOutputStream(new FileOutputStream(currentDir + "//src//main//resources//example-bad-model.dat"));
            model.serialize(modelOut);
        } catch (IOException e) {
            // Failed to save model
            e.printStackTrace();
        } finally {
            if (modelOut != null) {
                try {
                    modelOut.close();
                } catch (IOException e) {
                    // Failed to correctly save model.
                    // Written model might be invalid.
                    e.printStackTrace();
                }
```

**Comment by AlexTitovWork** [comment]
I checked code below , it is worked, model generated:
```
            String currentDir = new File("").getAbsolutePath();
            new BufferedOutputStream(new FileOutputStream(currentDir + "example-bad-model.dat"));
            new File(currentDir, "//example-bad-model.dat");
            new FileOutputStream(currentDir.toString() + "//example-bad-model.dat");
//            openFileOutput("example-bad-model.dat", Context.MODE_PRIVATE); // i think problem here, in Android class "android.content.Context" 

```

**Comment by mouri11** [comment]
Great. Thanks for your help.
